"""Project scaffolding — creates directory structures and boilerplate."""

import logging
import os
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..core.config import Config
from ..core.types import Solution, Task

logger = logging.getLogger(__name__)


# Templates for common project types
PYTHON_PROJECT_TEMPLATE = {
    "pyproject.toml": '''[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{name}"
version = "0.1.0"
description = "Auto-generated by ASSBRAIN"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "torch",
]

[project.optional-dependencies]
dev = ["pytest", "black", "mypy", "ruff"]
''',
    "README.md": "# {name}\n\nAuto-generated project.\n",
    "src/__init__.py": "",
    "tests/__init__.py": "",
    "tests/test_main.py": "import pytest\n\ndef test_placeholder():\n    assert True\n",
}

NEXTJS_PROJECT_TEMPLATE = {
    "package.json": '''{
  "name": "{name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "^14.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "typescript": "^5.3.0",
    "@types/node": "^20.0.0",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "tailwindcss": "^3.4.0",
    "postcss": "^8.4.0",
    "autoprefixer": "^10.4.0",
    "eslint": "^8.0.0",
    "eslint-config-next": "^14.0.0"
  }
}''',
    "next.config.js": '''/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}
module.exports = nextConfig
''',
    "tsconfig.json": '''{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}''',
    "tailwind.config.ts": '''import type { Config } from 'tailwindcss'
const config: Config = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}', './app/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: { extend: {} },
  plugins: [],
}
export default config
''',
    "postcss.config.js": '''module.exports = {
  plugins: { tailwindcss: {}, autoprefixer: {} },
}''',
    "app/globals.css": '''@tailwind base;
@tailwind components;
@tailwind utilities;
''',
    "app/layout.tsx": '''export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
''',
    "app/page.tsx": '''export default function Home() {
  return <main className="p-8"><h1 className="text-2xl font-bold">Hello ASSBRAIN</h1></main>
}
''',
}


class ProjectScaffold:
    """Creates project directory structures from templates."""

    def __init__(self, config: Config):
        self.base_dir = config.projects_dir
        self.base_dir.mkdir(parents=True, exist_ok=True)

    def scaffold(self, name: str, template: str = "python") -> Path:
        """Create a new project directory from a template."""
        project_dir = self.base_dir / name
        project_dir.mkdir(parents=True, exist_ok=True)

        templates = {
            "python": PYTHON_PROJECT_TEMPLATE,
            "nextjs": NEXTJS_PROJECT_TEMPLATE,
        }
        chosen = templates.get(template, PYTHON_PROJECT_TEMPLATE)

        for rel_path, content in chosen.items():
            file_path = project_dir / rel_path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content.format(name=name))

        logger.info(f"📁 Scaffolded {template} project at {project_dir}")
        return project_dir

    def write_solution(self, project_dir: Path, solution: Solution) -> None:
        """Write solution files into a project directory."""
        # Write main code if no files dict
        if not solution.files and solution.code:
            if solution.language == "python":
                target = project_dir / "src" / "main.py"
            elif solution.language in ("typescript", "javascript"):
                target = project_dir / "app" / "page.tsx"
            else:
                target = project_dir / "main.txt"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(solution.code)
            logger.info(f"  Written main code to {target}")
            return

        # Write all files from solution
        for rel_path, content in solution.files.items():
            # Sanitize path
            safe_path = Path(rel_path).name if ".." in rel_path else rel_path
            file_path = project_dir / safe_path
            file_path.parent.mkdir(parents=True, exist_ok=True)
            file_path.write_text(content)
            logger.info(f"  Written {file_path}")

    def detect_project_type(self, solution: Solution) -> str:
        if solution.language in ("typescript", "javascript"):
            return "nextjs"
        if "import React" in solution.code or "export default" in solution.code:
            return "nextjs"
        return "python"
