"""Tool execution engine for ASSBRAIN's function calling."""

import json
import logging
import os
import subprocess
import tempfile
from typing import Any, Callable, Dict, List, Optional

from rich.console import Console

logger = logging.getLogger(__name__)
console = Console()


class ToolExecutor:
    """Executes tool calls generated by the model."""

    def __init__(self):
        self.tools: Dict[str, Callable] = {}
        self._register_defaults()

    def _register_defaults(self):
        """Register built-in tools."""
        self.register("bash", self._bash)
        self.register("python", self._python)
        self.register("read_file", self._read_file)
        self.register("write_file", self._write_file)
        self.register("list_dir", self._list_dir)
        self.register("search_code", self._search_code)
        self.register("pip_install", self._pip_install)
        self.register("web_search", self._web_search_stub)

    def register(self, name: str, fn: Callable):
        self.tools[name] = fn

    def execute(self, tool_call: Dict[str, Any]) -> Any:
        """Execute a single tool call."""
        name = tool_call.get("name", tool_call.get("tool", ""))
        arguments = tool_call.get("arguments", tool_call.get("args", tool_call.get("params", {})))
        if isinstance(arguments, str):
            try:
                arguments = json.loads(arguments)
            except json.JSONDecodeError:
                return {"error": f"Invalid arguments JSON: {arguments}"}

        if name not in self.tools:
            return {"error": f"Unknown tool: {name}. Available: {list(self.tools.keys())}"}

        logger.info(f"🔧 Executing tool: {name}({arguments})")
        try:
            result = self.tools[name](**arguments)
            return {"success": True, "output": result}
        except Exception as e:
            logger.exception(f"Tool {name} failed")
            return {"error": str(e)}

    def execute_batch(self, tool_calls: List[Dict[str, Any]]) -> List[Any]:
        return [self.execute(tc) for tc in tool_calls]

    # ---- Built-in Tools ----

    def _bash(self, command: str, timeout: int = 60) -> str:
        result = subprocess.run(
            command, shell=True, capture_output=True, text=True, timeout=timeout
        )
        output = result.stdout
        if result.stderr:
            output += f"\n[stderr]\n{result.stderr}"
        if result.returncode != 0:
            output += f"\n[exit code {result.returncode}]"
        return output

    def _python(self, code: str) -> str:
        with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
            f.write(code)
            path = f.name
        try:
            result = subprocess.run(
                ["python", path], capture_output=True, text=True, timeout=60
            )
            output = result.stdout
            if result.stderr:
                output += f"\n[stderr]\n{result.stderr}"
            return output
        finally:
            os.unlink(path)

    def _read_file(self, path: str, limit: int = 2000) -> str:
        try:
            with open(path, "r", encoding="utf-8", errors="ignore") as f:
                lines = f.readlines()[:limit]
                return "".join(lines)
        except Exception as e:
            return f"Error reading {path}: {e}"

    def _write_file(self, path: str, content: str) -> str:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return f"Wrote {len(content)} chars to {path}"

    def _list_dir(self, path: str = ".") -> str:
        try:
            entries = os.listdir(path)
            return "\n".join(entries)
        except Exception as e:
            return f"Error: {e}"

    def _search_code(self, query: str, path: str = ".", ext: str = ".py") -> str:
        try:
            result = subprocess.run(
                ["grep", "-r", "-n", "--include", f"*{ext}", query, path],
                capture_output=True, text=True, timeout=30,
            )
            return result.stdout or "No matches found"
        except Exception as e:
            return f"Error: {e}"

    def _pip_install(self, package: str) -> str:
        result = subprocess.run(
            ["pip", "install", package], capture_output=True, text=True, timeout=120
        )
        return result.stdout + (f"\n[stderr]\n{result.stderr}" if result.stderr else "")

    def _web_search_stub(self, query: str) -> str:
        return f"[Web search not configured. Query: {query}]"

    def get_tool_descriptions(self) -> str:
        """Return JSON schema descriptions for all tools."""
        schemas = [
            {
                "name": "bash",
                "description": "Execute a bash shell command",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "command": {"type": "string", "description": "The bash command to run"},
                        "timeout": {"type": "integer", "description": "Timeout in seconds", "default": 60}
                    },
                    "required": ["command"]
                }
            },
            {
                "name": "python",
                "description": "Execute Python code in a subprocess",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "code": {"type": "string", "description": "Python code to execute"}
                    },
                    "required": ["code"]
                }
            },
            {
                "name": "read_file",
                "description": "Read contents of a file",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "limit": {"type": "integer", "default": 2000}
                    },
                    "required": ["path"]
                }
            },
            {
                "name": "write_file",
                "description": "Write content to a file",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "content": {"type": "string"}
                    },
                    "required": ["path", "content"]
                }
            },
            {
                "name": "list_dir",
                "description": "List directory contents",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "path": {"type": "string", "default": "."}
                    }
                }
            },
            {
                "name": "search_code",
                "description": "Search for code patterns using grep",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "path": {"type": "string", "default": "."},
                        "ext": {"type": "string", "default": ".py"}
                    },
                    "required": ["query"]
                }
            },
            {
                "name": "pip_install",
                "description": "Install a Python package via pip",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "package": {"type": "string"}
                    },
                    "required": ["package"]
                }
            },
        ]
        return json.dumps(schemas, indent=2)
